# Generated by Django 6.0.1 on 2026-01-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('koszt_energii_mwh', models.FloatField(help_text='Koszt energii w PLN/MWh')),
            ],
        ),
        migrations.CreateModel(
            name='ZrodloCiepla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('woda', 'Woda'), ('powietrze', 'Powietrze'), ('spaliny', 'Spaliny'), ('olej', 'Olej Termalny')], max_length=20)),
                ('czas_pracy_h_rok', models.IntegerField()),
                ('nominalna_temp', models.FloatField(default=100.0, help_text='Typowa temperatura pracy [°C]')),
                ('nominalny_przeplyw', models.FloatField(default=1.0, help_text='Typowy przepływ [kg/s]')),
                ('aktywny_symulator', models.BooleanField(default=False, help_text='Czy generować dane automatycznie?')),
                ('zaklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zaklad')),
            ],
        ),
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wpisu', models.DateTimeField(auto_now_add=True)),
                ('typ_wpisu', models.CharField(choices=[('MANUAL', 'Ręczny'), ('SENSOR', 'Czujnik (Symulacja)')], default='MANUAL', max_length=10)),
                ('temp_zrodla', models.FloatField()),
                ('temp_otoczenia', models.FloatField(default=20.0)),
                ('przeplyw_masowy', models.FloatField()),
                ('sprawnosc_odzysku', models.FloatField(default=0.85)),
                ('zrodlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zrodlociepla')),
            ],
        ),
    ]
